[package]
name = "skkdic-sort"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/mtgto/skkdic-sort.rs"
repository = "https://github.com/mtgto/skkdic-sort.rs"
description = "sort utf-8 skkdict"
authors = ["mtgto <hogerappa@gmail.com>"]
readme = "README.md"
license = "MIT"
